using PaymentServices.Shared.Enums;

namespace PaymentServices.Shared.Messages;

/// <summary>
/// The canonical Service Bus message envelope that flows through the entire
/// PaymentServices pipeline. Each function enriches this message and publishes
/// it to the next subscription.
/// </summary>
public sealed class PaymentMessage
{
    // -------------------------------------------------------------------------
    // Identifiers
    // -------------------------------------------------------------------------

    /// <summary>External transaction ID from RTPSend / Evolve.</summary>
    public required string EvolveId { get; init; }

    /// <summary>Platform identifier (Curio, Stripe, Earnin etc.).</summary>
    public required string FintechId { get; init; }

    /// <summary>Internal correlation ID for distributed tracing across all functions.</summary>
    public required string CorrelationId { get; init; }

    // -------------------------------------------------------------------------
    // Transaction details
    // -------------------------------------------------------------------------

    /// <summary>Transaction amount as a string to avoid floating-point precision loss.</summary>
    public required string Amount { get; init; }

    /// <summary>Tax ID (SSN or EIN) of the transacting party.</summary>
    public required string TaxId { get; init; }

    /// <summary>Indicates whether the transacting party is a business.</summary>
    public bool UserIsBusiness { get; init; }

    // -------------------------------------------------------------------------
    // Account parties
    // -------------------------------------------------------------------------

    /// <summary>Source account details, enriched by AccountResolution.</summary>
    public required PaymentParty Source { get; set; }

    /// <summary>Destination account details, enriched by AccountResolution.</summary>
    public required PaymentParty Destination { get; set; }

    // -------------------------------------------------------------------------
    // Pipeline state
    // -------------------------------------------------------------------------

    /// <summary>Current state of the transaction in the pipeline.</summary>
    public TransactionState State { get; set; } = TransactionState.Received;

    /// <summary>UTC timestamp when the Gateway first received this message.</summary>
    public DateTimeOffset ReceivedAt { get; init; } = DateTimeOffset.UtcNow;

    /// <summary>UTC timestamp of the last state change.</summary>
    public DateTimeOffset LastUpdatedAt { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Human-readable reason for failure states. Populated by the failing function
    /// before publishing to EventNotification.
    /// </summary>
    public string? FailureReason { get; set; }

    // -------------------------------------------------------------------------
    // Transfer output — populated by Transfer function
    // -------------------------------------------------------------------------

    /// <summary>Internal transaction ID generated by the Transfer function.</summary>
    public string? EveTransactionId { get; set; }

    /// <summary>Ledger entry gluId for the source (debit) side.</summary>
    public string? GluIdSource { get; set; }

    /// <summary>Ledger entry gluId for the destination (credit) side.</summary>
    public string? GluIdDestination { get; set; }

    /// <summary>Compliance flags returned from TMS check.</summary>
    public IReadOnlyList<string> TransactionFlags { get; set; } = [];
}

/// <summary>
/// Represents one party (source or destination) in a payment transaction.
/// Initially populated from the incoming request; enriched by AccountResolution and Compliance.
/// </summary>
public sealed class PaymentParty
{
    // -------------------------------------------------------------------------
    // From request
    // -------------------------------------------------------------------------

    public required string AccountNumber { get; init; }
    public required string RoutingNumber { get; init; }
    public required PartyName Name { get; init; }
    public PartyAddress? Address { get; init; }
    public string? PhoneNumber { get; init; }

    // -------------------------------------------------------------------------
    // Enriched by AccountResolution
    // -------------------------------------------------------------------------

    /// <summary>Cosmos DB document ID of the resolved Account.</summary>
    public string? AccountId { get; set; }

    /// <summary>Cosmos DB document ID of the resolved Ledger linked to the account.</summary>
    public string? LedgerId { get; set; }

    /// <summary>Cosmos DB document ID of the RemoteAccount.</summary>
    public string? RemoteAccountId { get; set; }

    /// <summary>Cosmos DB document ID of the resolved Entity.</summary>
    public string? EntityId { get; set; }

    // -------------------------------------------------------------------------
    // Enriched by Compliance
    // -------------------------------------------------------------------------

    public KycOutcome KycOutcome { get; set; } = KycOutcome.Unknown;
    public TmsOutcome TmsOutcome { get; set; } = TmsOutcome.Unknown;

    /// <summary>Alloy entity token — used for KYC/TMS correlation.</summary>
    public string? AlloyEntityToken { get; set; }
}

/// <summary>Name of a party — either individual or business.</summary>
public sealed class PartyName
{
    public string? First { get; init; }
    public string? Last { get; init; }
    public string? Company { get; init; }

    public bool IsBusiness => !string.IsNullOrWhiteSpace(Company);
}

/// <summary>Address of a party.</summary>
public sealed class PartyAddress
{
    public string? Line1 { get; init; }
    public string? City { get; init; }
    public string? State { get; init; }
    public string? PostalCode { get; init; }
    public string? Country { get; init; }
}
